// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/booking_entity.dart';
import 'models/favorite_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 506204465699262922),
    name: 'BookingEntity',
    lastPropertyId: const obx_int.IdUid(8, 715786692391068368),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6528405355464951196),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7546711604992719418),
        name: 'hotelId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3742222186167609400),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9080722141958866991),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 288608378981647187),
        name: 'totalPrice',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4328120364272168851),
        name: 'hotelTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2960009377409984567),
        name: 'hotelPlace',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 715786692391068368),
        name: 'hotelPicture',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3799799457236826484),
    name: 'FavoriteEntity',
    lastPropertyId: const obx_int.IdUid(2, 2223057209943291237),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4948668884196465112),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2223057209943291237),
        name: 'hotelId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 3799799457236826484),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BookingEntity: obx_int.EntityDefinition<BookingEntity>(
      model: _entities[0],
      toOneRelations: (BookingEntity object) => [],
      toManyRelations: (BookingEntity object) => {},
      getId: (BookingEntity object) => object.id,
      setId: (BookingEntity object, int id) {
        object.id = id;
      },
      objectToFB: (BookingEntity object, fb.Builder fbb) {
        final hotelTitleOffset = fbb.writeString(object.hotelTitle);
        final hotelPlaceOffset = fbb.writeString(object.hotelPlace);
        final hotelPictureOffset = fbb.writeString(object.hotelPicture);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.hotelId);
        fbb.addInt64(2, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(3, object.endDate.millisecondsSinceEpoch);
        fbb.addInt64(4, object.totalPrice);
        fbb.addOffset(5, hotelTitleOffset);
        fbb.addOffset(6, hotelPlaceOffset);
        fbb.addOffset(7, hotelPictureOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final hotelIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final startDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final endDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final totalPriceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final hotelTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final hotelPlaceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final hotelPictureParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = BookingEntity(
          id: idParam,
          hotelId: hotelIdParam,
          startDate: startDateParam,
          endDate: endDateParam,
          totalPrice: totalPriceParam,
          hotelTitle: hotelTitleParam,
          hotelPlace: hotelPlaceParam,
          hotelPicture: hotelPictureParam,
        );

        return object;
      },
    ),
    FavoriteEntity: obx_int.EntityDefinition<FavoriteEntity>(
      model: _entities[1],
      toOneRelations: (FavoriteEntity object) => [],
      toManyRelations: (FavoriteEntity object) => {},
      getId: (FavoriteEntity object) => object.id,
      setId: (FavoriteEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FavoriteEntity object, fb.Builder fbb) {
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.hotelId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final hotelIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final object = FavoriteEntity(id: idParam, hotelId: hotelIdParam);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BookingEntity] entity fields to define ObjectBox queries.
class BookingEntity_ {
  /// See [BookingEntity.id].
  static final id = obx.QueryIntegerProperty<BookingEntity>(
    _entities[0].properties[0],
  );

  /// See [BookingEntity.hotelId].
  static final hotelId = obx.QueryIntegerProperty<BookingEntity>(
    _entities[0].properties[1],
  );

  /// See [BookingEntity.startDate].
  static final startDate = obx.QueryDateProperty<BookingEntity>(
    _entities[0].properties[2],
  );

  /// See [BookingEntity.endDate].
  static final endDate = obx.QueryDateProperty<BookingEntity>(
    _entities[0].properties[3],
  );

  /// See [BookingEntity.totalPrice].
  static final totalPrice = obx.QueryIntegerProperty<BookingEntity>(
    _entities[0].properties[4],
  );

  /// See [BookingEntity.hotelTitle].
  static final hotelTitle = obx.QueryStringProperty<BookingEntity>(
    _entities[0].properties[5],
  );

  /// See [BookingEntity.hotelPlace].
  static final hotelPlace = obx.QueryStringProperty<BookingEntity>(
    _entities[0].properties[6],
  );

  /// See [BookingEntity.hotelPicture].
  static final hotelPicture = obx.QueryStringProperty<BookingEntity>(
    _entities[0].properties[7],
  );
}

/// [FavoriteEntity] entity fields to define ObjectBox queries.
class FavoriteEntity_ {
  /// See [FavoriteEntity.id].
  static final id = obx.QueryIntegerProperty<FavoriteEntity>(
    _entities[1].properties[0],
  );

  /// See [FavoriteEntity.hotelId].
  static final hotelId = obx.QueryIntegerProperty<FavoriteEntity>(
    _entities[1].properties[1],
  );
}
